apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hello-world-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-hello-world
  template:
    metadata:
      labels:
        app: go-hello-world
    spec:
      containers:
      - name: go-hello-world
        image: go-hello-world-app:minikube
        ports:
        - containerPort: 8080
